### ISSUE TITLE
Crucial P5 boot time

### ISSUE THREAD

**Issue by SamCsquared** [osx86-ijb/MSI-B450-Tomahawk-Max-Ryzen5-3600-macOS#1]
Hi there, is nvme drive Crucial P5 well supported by opencore in Bigsur? What is your boot time?(From os picker to login)? Thank you for answering as I would like to pull the trigger on a nvme drive as well but I read that few are quite anti-mac.

**Comment by SamCsquared** [comment]
Some reports about 10s, others could take up to 30s

**Comment by SamCsquared** [comment]
Some reports about 10s, others could take up to 30s

**Comment by SamCsquared** [comment]
Some reports about 10s, others could take up to 30s

**Comment by osx86-ijb** [comment]
This repository is for an EFI for this motherboard, not an NVMe hackintosh bootloader support repository (no offense). I don't use that drive. Boot times are also dependent upon specific hardware that is in use. Please don't spam issues that aren't dealing with this specific hardware. Thanks.
